name: trigger gitlab job
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name:  curl
      run: curl --write-out '%{http_code}' --silent --output /dev/null -d "token=${{ secrets.FORGEMIA_TOKEN }}&ref=master&variables[GITHUB_COMMIT_SHA]=$GITHUB_SHA" -X POST https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
  update_upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name:  curl
      run: |
        git clone https://arnaud.charleroy:${{ secrets.FORGEMIA_TOKEN }}@forgemia.inra.fr/OpenSILEX/opensilex-dev.git
        git remote add upstream https://github.com/OpenSILEX/opensilex-dev.git
        git fetch origin
        git checkout upstream
        git merge pull upstream upstream
        git push origin upstream
